apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      # Change for K8s provider:
  storageClassName: default